name: CI/CD Pipeline IAS

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  # ==========================================
  # 1. TRABAJO DE INTEGRACIÓN CONTINUA (CI)
  # ==========================================
  continuous-integration:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias de desarrollo
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Ejecutar Pruebas Unitarias
        env:
          PYTHONPATH: .
        run: pytest tests/unit

      - name: Ejecutar Pruebas de Integración
        env:
          PYTHONPATH: .
        run: |
          # Si tenés la carpeta creada ejecuta esto, sino busca archivos de integración
          if [ -d "tests/integration" ]; then pytest tests/integration; else echo "No hay tests de integración específicos todavía"; fi

      - name: Análisis Estático de Seguridad (Bandit)
        run: bandit -r app/ -ll

  # ==========================================
  # 2. TRABAJO DE DESPLIEGUE CONTINUO (CD)
  # ==========================================
  deploy-environments:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar a Entorno DEV
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "Haciendo deploy a la API de Desarrollo..."
          curl -f "${{ secrets.RENDER_DEPLOY_HOOK_DEV }}"

      - name: Desplegar a Entorno QA
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Haciendo deploy a la API de QA..."
          curl -f "${{ secrets.RENDER_DEPLOY_HOOK_QA }}"
