name: CI/CD Pipeline IAS

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  # ==========================================
  # CI: INTEGRACIÓN CONTINUA (Solo en Pull Requests)
  # ==========================================
  ci-tests:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Ejecutar pruebas unitarias e integración
        env:
          PYTHONPATH: .
        run: |
          pytest tests/unit/
          pytest tests/integration/

      - name: Análisis de código con Bandit
        run: bandit -r app/

      - name: Ejecutar Tests de Seguridad (Solo PR de develop hacia main)
        if: github.base_ref == 'main'
        env:
          PYTHONPATH: .
        run: pytest tests/security/

  # ==========================================
  # CD: DESPLIEGUE CONTINUO (Solo al hacer merge/push)
  # ==========================================
  
  # Deploy automático a DEV cuando llega código a develop
  deploy-dev:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
  #  if: github.event_name == 'push' && github.ref == 'refs/heads/develop' # solo corre en merge/push a develop
    steps:
      - name: Disparar deploy en Render DEV
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_DEV }}"

  # Deploy automático a QA cuando llega código a main
  deploy-qa:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Disparar deploy en Render QA
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_QA }}"

  # Deploy manual a PRD (Requiere aprobación del Release Manager)
  deploy-prod:
    needs: deploy-qa
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Disparar deploy en Render PRD
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_PRD }}"
