name: CI/CD Pipeline

on:
  push:
    branches:
      - main      # Dispara qa y luego pide permiso para prd
      - develop   # Dispara dev automáticamente
  pull_request:
    branches:
      - main      # Dispara ci al hacer pr hacia main
      - develop   # Dispara ci al hacer pr hacia develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: analizar seguridad con Bandit (Solo en pr a main)
        # Se asegura de correr  si es un Pull Request apuntando a main
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        run: |
          bandit -r ./ -ll -ii

      - name: Ejecutar pruebas unitarias y de integración
        env:
          PYTHONPATH: .
        run: |
          pytest tests/unit/
          pytest tests/integration/

  deploy-dev:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop' # solo corre en merge/push a develop
    steps:
      - name: Disparar deploy en Render (Entorno Dev)
        run: |
          curl "${{ secrets.RENDER_DEPLOY_HOOK_DEV }}"

  deploy-qa:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Solo corre en merge/push a main
    steps:
      - name: Disparar deploy en Render (Entorno QA)
        run: |
          curl "${{ secrets.RENDER_DEPLOY_HOOK_QA }}"

  deploy-prod:
    needs: [test, deploy-qa] # Espera a que QA esté listo antes de pedir aprobación
    runs-on: ubuntu-latest
    environment: production # ESTO FRENA EL DEPLOY Y TE PIDE APROBACIÓN MANUAL
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Disparar deploy en Render (Entorno Prod)
        run: |
          curl "${{ secrets.RENDER_DEPLOY_HOOK_PRD }}"
